# https://stackoverflow.com/questions/67134410/how-to-test-my-dockerfile-for-my-python-project-using-github-actions
name: Docker build and test

on: 
  pull_request

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t beryl .
     - name: Run tests inside the container
       run: docker exec -it beryl pytest